spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news_management
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yml
    enabled: true
  data:
    redis:
      host: redis-cache
      port: 6379

security:
  token:
    secret-key: 123456789ABC123456789ABC987654321ABC987654321
    expiration: 86400000